export enum ApiPermission {
  ADD_MEDIA = 'ADD_MEDIA',
  READ_MEDIA = 'READ_MEDIA',
  REMOVE_MEDIA = 'REMOVE_MEDIA',
  UPDATE_MEDIA = 'UPDATE_MEDIA',
  RESYNC_DATABASE = 'RESYNC_DATABASE',
  CREATE_USER = 'CREATE_USER',
}
