import { test, expect } from '../fixtures';

/**
 * The machine-facing surfaces: the sitemaps, the blog feed and robots.txt.
 *
 * Nothing covered these, and they are the worst kind of thing to leave
 * uncovered -- no human opens them, so a break is invisible until traffic
 * drops or a feed reader goes quiet weeks later. They are also the surfaces
 * most likely to break by accident, because they are generated from the route
 * table and the content directory rather than written by hand.
 *
 * Assertions are on STRUCTURE and content type rather than on any particular
 * URL being present, so the suite does not fail every time a page is added --
 * except for the handful of paths that are load-bearing for indexing.
 */
test.describe('sitemap', () => {
  // Staging deliberately disables sitemap generation in nuxt.config.ts: it is
  // not an indexable origin and should not spend backend capacity building a
  // crawler inventory. Production release smoke includes this spec instead.
  test.skip(
    process.env.E2E_BASE_URL?.includes('stg.nadeshiko.co') ?? false,
    'sitemaps are intentionally disabled on staging',
  );

  test('the index is served as XML', async ({ request }) => {
    // A sitemap served as `text/html` is one Google fetches and discards.
    const response = await request.get('/sitemap.xml');

    expect(response.status()).toBe(200);
    expect(response.headers()['content-type']).toContain('xml');
  });

  test('the index lists a sitemap per indexed locale', async ({ request }) => {
    // The per-locale split is what keeps the English and Spanish trees from
    // being advertised as one, which is what the hreflang pairs depend on.
    const body = await (await request.get('/sitemap.xml')).text();

    expect(body).toContain('<sitemapindex');
    expect(body).toContain('/__sitemap__/en.xml');
    expect(body).toContain('/__sitemap__/es.xml');
  });

  for (const locale of ['en', 'es']) {
    test(`the ${locale} sitemap is well-formed XML with entries in it`, async ({ request }) => {
      const response = await request.get(`/__sitemap__/${locale}.xml`);
      const body = await response.text();

      expect(response.status()).toBe(200);
      expect(response.headers()['content-type']).toContain('xml');
      expect(body).toContain('<urlset');
      expect(body.match(/<loc>/g)?.length ?? 0).toBeGreaterThan(0);
    });

    test(`every url in the ${locale} sitemap is inside that locale`, async ({ request }) => {
      // A cross-locale entry advertises a URL that redirects, which spends a
      // crawl on a hop and splits the ranking between the two.
      const body = await (await request.get(`/__sitemap__/${locale}.xml`)).text();
      const paths = [...body.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => new URL(m[1]).pathname);

      expect(paths.length).toBeGreaterThan(0);
      for (const path of paths) {
        expect(path === `/${locale}` || path.startsWith(`/${locale}/`)).toBe(true);
      }
    });

    test(`the ${locale} sitemap has no duplicate urls`, async ({ request }) => {
      // A duplicated entry is how a generated sitemap says a page is twice as
      // important as it is, and it is invisible by inspection.
      const body = await (await request.get(`/__sitemap__/${locale}.xml`)).text();
      const locs = [...body.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);

      expect(new Set(locs).size).toBe(locs.length);
    });
  }

  test('the sitemap advertises the pages the site is found by', async ({ request }) => {
    // The entry points a crawler is meant to start from. Everything else is
    // reached from these.
    const body = await (await request.get('/__sitemap__/en.xml')).text();

    const paths = [...body.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => new URL(m[1]).pathname);
    expect(paths).toEqual(expect.arrayContaining(['/en', '/en/media', '/en/about', '/en/blog', '/en/stats']));
  });

  test('does not advertise the search route, whose query URLs are unbounded', async ({ request }) => {
    // Deliberate, and the counterpart to `search-redirect`'s junk-collapsing:
    // `/search/:query` is an infinite family of pages generated by whatever
    // anyone types, and inviting a crawler into it is what produced the 14k
    // requests a day that middleware exists to stop. Asserted so that adding
    // the route back to the sitemap has to be a decision rather than a default.
    const body = await (await request.get('/__sitemap__/en.xml')).text();

    const paths = [...body.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => new URL(m[1]).pathname);
    expect(paths.some((path) => path === '/en/search' || path.startsWith('/en/search/'))).toBe(false);
  });
});

test.describe('blog feed', () => {
  test('is served as RSS', async ({ request }) => {
    // A feed reader looks at the content type before the body.
    const response = await request.get('/en/blog/rss.xml');

    expect(response.status()).toBe(200);
    expect(response.headers()['content-type']).toContain('rss+xml');
  });

  test('carries a channel with posts in it', async ({ request }) => {
    const body = await (await request.get('/en/blog/rss.xml')).text();

    expect(body).toContain('<rss');
    expect(body).toContain('<channel>');
    expect(body.match(/<item>/g)?.length ?? 0).toBeGreaterThan(0);
  });

  test('every item has the three fields a reader needs to show it', async ({ request }) => {
    // A title with no link is an entry nobody can open; a missing date sorts
    // to the top or the bottom of every feed reader in the world.
    const body = await (await request.get('/en/blog/rss.xml')).text();
    const items = [...body.matchAll(/<item>([\s\S]*?)<\/item>/g)].map((m) => m[1]);

    expect(items.length).toBeGreaterThan(0);
    for (const item of items) {
      expect(item).toMatch(/<title>/);
      expect(item).toMatch(/<link>/);
      expect(item).toMatch(/<pubDate>/);
    }
  });

  test('items carry a permanent guid, so a re-publish is not a new post', async ({ request }) => {
    // Without a stable guid every regeneration re-notifies every subscriber.
    const body = await (await request.get('/en/blog/rss.xml')).text();
    const guids = [...body.matchAll(/<guid[^>]*>([^<]+)<\/guid>/g)].map((m) => m[1]);

    expect(guids.length).toBeGreaterThan(0);
    expect(new Set(guids).size).toBe(guids.length);
  });

  test('the Spanish feed is served too', async ({ request }) => {
    const response = await request.get('/es/blog/rss.xml');

    expect(response.status()).toBe(200);
    expect(await response.text()).toContain('<channel>');
  });

  test('links back to itself, which is how a reader finds the canonical feed', async ({ request }) => {
    const body = await (await request.get('/en/blog/rss.xml')).text();

    expect(body).toContain('rel="self"');
  });
});

test.describe('robots.txt', () => {
  test('is served as plain text', async ({ request }) => {
    const response = await request.get('/robots.txt');

    expect(response.status()).toBe(200);
    expect(response.headers()['content-type']).toContain('text/plain');
  });

  test('names at least one user-agent group', async ({ request }) => {
    // An empty robots.txt and a broken one look the same to a crawler, and
    // both are served with a 200.
    const body = await (await request.get('/robots.txt')).text();

    expect(body).toMatch(/User-agent:/i);
  });
});

test.describe('health', () => {
  test('/up answers ok', async ({ request }) => {
    // Kamal decides whether a deploy succeeded from this, so it is worth one
    // assertion that it is JSON and says so.
    const response = await request.get('/up');

    expect(response.status()).toBe(200);
    expect(response.headers()['content-type']).toContain('json');
  });
});
