version: 2
updates:
  - package-ecosystem: bun
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: bun
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: bun
    directory: /discord
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: bun
    directory: /infra/seed-worker
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
