servers:
  web:
    hosts:
      - nadeshiko

registry:
  server: ghcr.io
  username: kamal
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

ssh:
  user: docker

aliases:
  toolbox-console: accessory exec toolbox -i --cmd "bash"
  logs: app logs -f
