image: nadeshiko-backend-dev
service: nadeshiko-backend-prod

proxy:
  ssl: true
  host: api.nadeshiko.co
  forward_headers: true

env:
  secret:
    - ALLOWED_WEBSITE_URLS
    - API_KEY_MASTER
    - BETTER_AUTH_SECRET

    - EMAIL_API_NADEDB
    - USERNAME_API_NADEDB

    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - POSTGRES_ADMIN_USER
    - POSTGRES_ADMIN_PASSWORD

    - ELASTICSEARCH_USER
    - ELASTICSEARCH_PASSWORD
    - ELASTICSEARCH_ADMIN_USER
    - ELASTICSEARCH_ADMIN_PASSWORD

    - DISCORD_CLIENT_ID
    - DISCORD_CLIENT_SECRET
    - DISCORD_REDIRECT_URI

    - ID_OAUTH_GOOGLE
    - SECRET_OAUTH_GOOGLE
    - URI_ALLOWED_GOOGLE

    - SES_AWS_REGION
    - SES_AWS_ACCESS_KEY_ID
    - SES_AWS_SECRET_ACCESS_KEY

  clear:
    ENVIRONMENT: prod
    PORT: 80
    BASE_URL: https://api.nadeshiko.co
    COOKIE_DOMAIN: .nadeshiko.co

    SES_FROM_EMAIL: noreply@nadeshiko.co
    SES_FROM_NAME: Nadeshiko

    POSTGRES_HOST: "nadeshiko-backend-postgres"
    POSTGRES_PORT: 5432

    ELASTICSEARCH_HOST: "http://nadeshiko-backend-elasticsearch:9200"
    ELASTICSEARCH_INDEX: nadedb_prod

    R2_BASE_URL: https://cdn.nadeshiko.co/media

