service: nadeshiko-backend-dev
image: brigadasos/nadeshiko-backend-dev

servers:
  web:
    cmd: sh -c 'bun run db:prepare && bun run start'

proxy:
  ssl: true
  host: api-dev.nadeshiko.co
  forward_headers: true

env:
  secret:
    - ALLOWED_WEBSITE_URLS
    - API_KEY_MASTER
    - BETTER_AUTH_SECRET

    - EMAIL_API_NADEDB
    - USERNAME_API_NADEDB
    - UUID_NAMESPACE

    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - POSTGRES_ADMIN_USER
    - POSTGRES_ADMIN_PASSWORD

    - ELASTICSEARCH_USER
    - ELASTICSEARCH_PASSWORD
    - ELASTICSEARCH_ADMIN_USER
    - ELASTICSEARCH_ADMIN_PASSWORD

    - DISCORD_CLIENT_ID
    - DISCORD_CLIENT_SECRET

    - ID_OAUTH_GOOGLE
    - SECRET_OAUTH_GOOGLE

    - SES_AWS_REGION
    - SES_AWS_ACCESS_KEY_ID
    - SES_AWS_SECRET_ACCESS_KEY
    - SES_FROM_EMAIL
    - SES_FROM_NAME

    - SENTRY_BACKEND_DSN

  clear:
    ENVIRONMENT: dev
    PORT: 80
    BASE_URL: https://dev.nadeshiko.co

    POSTGRES_HOST: "nadeshiko-backend-prod-postgres"
    POSTGRES_PORT: 5432

    ELASTICSEARCH_HOST: "http://nadeshiko-backend-prod-elasticsearch:9200"
    ELASTICSEARCH_INDEX: nadedb_dev

    R2_BASE_URL: https://cdn.nadeshiko.co

    OTEL_EXPORTER_OTLP_ENDPOINT: "http://nadeshiko-backend-prod-alloy:4318"
    OTEL_SERVICE_NAME: nadeshiko-backend-dev
