global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: "production"
    service: "nadeshiko"

otlp:
  keep_identifying_resource_attributes: true
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
    - deployment.environment
    - deployment.environment.name

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          instance: "prometheus"

  - job_name: "alloy"
    static_configs:
      - targets: ["nadeshiko-backend-prod-alloy:12345"]
        labels:
          instance: "alloy"

