[build]
  command = "npm run build"
  publish="dist"
  base = "frontend_v2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = ["https://avatars.githubusercontent.com/u/.*"]

[[headers]]
  for = "/*.jpg"
  [headers.values]
  Cache-Control = "no-transform"