service: nadeshiko-frontend-dev
image: nadeshiko-frontend-dev

proxy:
  ssl: true
  host: dev.nadeshiko.co
  app_port: 3000
  forward_headers: true

env:
  secret:
    - NUXT_NADESHIKO_API_KEY

  clear:
    NODE_ENV: dev 
    NUXT_APP_ENVIRONMENT: dev
    NUXT_BACKEND_INTERNAL_URL: https://api-dev.nadeshiko.co
    PORT: 3000
    LOG_LEVEL: info
