service: nadeshiko-frontend-prod
image: brigadasos/nadeshiko-frontend-prod

builder:
  args:
    NUXT_PUBLIC_ENVIRONMENT: prod
    SENTRY_ORG: david-afonso
    SENTRY_PROJECT: nadeshiko-frontend
  secrets:
    - SENTRY_FRONTEND_DSN
    - SENTRY_AUTH_TOKEN

proxy:
  ssl: true
  host: nadeshiko.co
  app_port: 3000
  forward_headers: true

env:
  secret:
    - NUXT_NADESHIKO_API_KEY
    - SENTRY_FRONTEND_DSN

  clear:
    NODE_ENV: prod 
    NUXT_BACKEND_INTERNAL_URL: https://api.nadeshiko.co
    PORT: 3000
    LOG_LEVEL: info

    OTEL_EXPORTER_OTLP_ENDPOINT: "http://nadeshiko-backend-prod-alloy:4318"
    OTEL_SERVICE_NAME: nadeshiko-frontend
