service: nadeshiko-frontend-dev
image: brigadasos/nadeshiko-frontend-dev

builder:
  args:
    NUXT_PUBLIC_ENVIRONMENT: development
    SENTRY_ORG: davafons
    SENTRY_PROJECT: nadeshiko-frontend
  secrets:
    - SENTRY_FRONTEND_DSN
    - SENTRY_AUTH_TOKEN

proxy:
  ssl: true
  host: dev.nadeshiko.co
  app_port: 3000
  forward_headers: true

env:
  secret:
    - NUXT_NADESHIKO_API_KEY
    - SENTRY_FRONTEND_DSN

  clear:
    NUXT_PUBLIC_ENVIRONMENT: development
    NODE_ENV: production
    NUXT_BACKEND_INTERNAL_URL: https://api-dev.nadeshiko.co
    PORT: 3000
    LOG_LEVEL: info

    OTEL_EXPORTER_OTLP_ENDPOINT: "http://host.docker.internal:4328"
    OTEL_SERVICE_NAME: nadeshiko-frontend-dev
    OTEL_SEMCONV_STABILITY_OPT_IN: http
