servers:
  web:
    hosts:
      - nadeshiko

registry:
  server: ghcr.io
  username: kamal
  password:
    - KAMAL_REGISTRY_PASSWORD

aliases:
  console: app exec --interactive --reuse "bash"
  logs: app logs -f

builder:
  arch: amd64

ssh:
  user: docker
