export enum AuthType {
  SESSION = 'session',
  API_KEY = 'api-key',
}

export enum ApiKeyKind {
  SERVICE = 'service',
  USER = 'user',
}

export enum ApiPermission {
  ADD_MEDIA = 'ADD_MEDIA',
  READ_MEDIA = 'READ_MEDIA',
  UPDATE_MEDIA = 'UPDATE_MEDIA',
  REMOVE_MEDIA = 'REMOVE_MEDIA',

  READ_PROFILE = 'READ_PROFILE',
  WRITE_PROFILE = 'WRITE_PROFILE',
  READ_ACTIVITY = 'READ_ACTIVITY',
  WRITE_ACTIVITY = 'WRITE_ACTIVITY',

  READ_COLLECTIONS = 'READ_COLLECTIONS',
  CREATE_COLLECTIONS = 'CREATE_COLLECTIONS',
  UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS',
  DELETE_COLLECTIONS = 'DELETE_COLLECTIONS',
}
