import { describe, it, expect, vi } from 'vitest';
import { cachedMedia, _resetMediaCacheForTests } from './mediaCache';
import { cachedSegment, _resetSegmentCacheForTests as _resetSegmentsForTests } from './segmentCache';
import { createPublicRouteMatcher } from '#shared/utils/backendSdk';
import { publicApiRoutes } from './generated/publicApiRoutes';

/**
 * The precondition that makes this cache safe, asserted rather than assumed.
 *
 * `cachedMedia` is keyed on the media publicId and NOTHING else, which is only
 * correct because every visitor's render fetches that route with the same
 * credential. That is not a property of this file -- it is decided in
 * `createInternalSdk`, which attaches the service key to allowlisted routes and
 * the VISITOR'S OWN COOKIE to everything else:
 *
 *     if (apiKey && isPublicRoute(method, pathname)) → Bearer <service key>
 *     else if (cookie)                              → the visitor's cookie
 *
 * So if `GET /v1/media/{mediaPublicId}` ever leaves the allowlist, SSR silently
 * starts authenticating that fetch AS THE READER, the response becomes
 * viewer-dependent, and a cache keyed on the publicId alone hands the first
 * reader's response to the next one. That is a data leak, not a stale page.
 *
 * `publicApiRoutes.ts` is AUTOGENERATED from the backend's OpenAPI security
 * definitions, so this can change without anyone touching the frontend at all:
 * add auth to the route in the backend spec, run `npm run generate:api`, and the
 * precondition is gone with nothing to notice it. This test is the notice.
 *
 * If it fails, do not edit the expectation. Either the route should still be
 * public (fix the backend spec), or it should not -- in which case `cachedMedia`
 * has to key on the reader's identity or be deleted.
 */
describe('cachedMedia safety precondition', () => {
  it('only caches a route the SSR SDK fetches with the shared service key', () => {
    const isPublicRoute = createPublicRouteMatcher(publicApiRoutes);
    expect(isPublicRoute('GET', '/v1/media/AbCdEfGhIjKl')).toBe(true);
  });

  it('discriminates -- so the assertion above is not vacuously true', () => {
    // Without this, a matcher that returned `true` for everything (an empty
    // allowlist compiles to exactly that kind of mistake) would keep the guard
    // above green while the precondition it guards was gone.
    const isPublicRoute = createPublicRouteMatcher(publicApiRoutes);
    expect(isPublicRoute('GET', '/v1/user/me')).toBe(false);
    expect(isPublicRoute('PATCH', '/v1/media/AbCdEfGhIjKl')).toBe(false);
  });
});

describe('cachedMedia', () => {
  it('serves a repeat lookup without calling the backend again', async () => {
    _resetMediaCacheForTests();
    const fetcher = vi.fn(async () => ({ publicId: 'med_1' }));

    const first = await cachedMedia('med_1', fetcher);
    const second = await cachedMedia('med_1', fetcher);

    expect(second).toEqual(first);
    expect(fetcher).toHaveBeenCalledTimes(1);
  });

  it('collapses concurrent renders of the same title into ONE call', async () => {
    // The property this cache exists for. Hundreds of sentences share one
    // title, so a crawler on fifty different permalinks of the same show
    // produces fifty simultaneous lookups of one media record -- every one of
    // them a miss under a plain TTL cache.
    _resetMediaCacheForTests();
    let resolveFetch: (v: unknown) => void = () => {};
    const fetcher = vi.fn(
      () =>
        new Promise((resolve) => {
          resolveFetch = resolve;
        }),
    );

    const inFlight = Array.from({ length: 50 }, () => cachedMedia('med_hot', fetcher));
    resolveFetch({ publicId: 'med_hot' });
    const results = await Promise.all(inFlight);

    expect(fetcher).toHaveBeenCalledTimes(1);
    expect(results).toHaveLength(50);
  });

  it('does not cache failures, and retries the next caller', async () => {
    _resetMediaCacheForTests();
    const fetcher = vi.fn().mockRejectedValueOnce(new Error('backend down')).mockResolvedValue({ publicId: 'med_1' });

    await expect(cachedMedia('med_1', fetcher)).rejects.toThrow('backend down');
    await expect(cachedMedia('med_1', fetcher)).resolves.toEqual({ publicId: 'med_1' });
    expect(fetcher).toHaveBeenCalledTimes(2);
  });

  it('holds the whole catalogue without evicting', async () => {
    // The measured catalogue is ~325 titles against a 5,000 cap, so under real
    // traffic this cache never evicts -- which is what makes the hit rate ~100%
    // rather than merely good.
    _resetMediaCacheForTests();
    for (let i = 0; i < 325; i++) {
      await cachedMedia(`med_${i}`, async () => ({ publicId: `med_${i}` }));
    }

    const fetcher = vi.fn(async () => ({ publicId: 'med_0' }));
    await cachedMedia('med_0', fetcher);
    expect(fetcher).not.toHaveBeenCalled();
  });

  it('does not share a store with the segment cache', async () => {
    // Segment and media public IDs come from the same 12-character alphabet, so
    // a shared store keyed on the bare ID would let one answer the other -- a
    // Media returned where a Segment was asked for, typed as a Segment. This is
    // the test that keeps `ssrCorpusCache`'s one-store-per-type rule honest.
    _resetMediaCacheForTests();
    _resetSegmentsForTests();

    const collidingId = 'AbCdEfGhIjKl';
    const segment = await cachedSegment(collidingId, async () => ({ kind: 'segment' }));
    const media = await cachedMedia(collidingId, async () => ({ kind: 'media' }));

    expect(segment).toEqual({ kind: 'segment' });
    expect(media).toEqual({ kind: 'media' });
  });
});
