services:
  postgres:
    container_name: nadeshiko-postgres
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - nadeshiko_db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432


  elasticsearch:
    build:
      context: .
      dockerfile: docker/Dockerfile.elasticsearch
    container_name: nadeshiko-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=${ELASTICSEARCH_ADMIN_PASSWORD}
      - cluster.routing.allocation.disk.threshold_enabled=false
      - network.host=127.0.0.1
      - http.host=0.0.0.0
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    volumes:
      - nadeshiko_elasticsearch_data:/usr/share/elasticsearch/data


volumes:
  nadeshiko_db:
  nadeshiko_elasticsearch_data:
