name: Bug Report
description: Report a bug or issue with Nadeshiko
title: "<Bug description>"
labels: ["needs-triage", "priority-high"]
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for for taking the time to report a bug! Please allow us to undesrtand the issue better by providing some information below

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: When I try to...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, I saw...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Nadeshiko is affected?
      options:
        - Nadeshiko (Webpage)
        - Backend (API)
        - Other
    validations:
      required: false

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using? (if applicable)
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
        - Not applicable
    validations:
      required: false

  - type: dropdown
    id: device
    attributes:
      label: Device
      description: Which device are you using?
      options:
        - Mobile (Android)
        - Mobile (iOS)
        - Desktop
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Error Messages
      description: If applicable, add screenshots or paste error messages to help explain the problem
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
    validations:
      required: false
