name: Feature Request
description: Suggest a new feature or enhancement for Nadeshiko
title: "<Feature description>"
type: "Feature"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a new feature!

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve?
      placeholder: Right now it painful to...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I've also thought about...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Nadeshiko does this feature relate to the most?
      options:
        - Nadeshiko (Webpage)
        - Backend (API)
        - Other
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request
    validations:
      required: false
