import { getMeter } from './telemetry';
import { BOT_CONFIG, getApplicationId } from './config';
import { createLogger } from './logger';

const log = createLogger('oauth-redirect-monitor');
const CHECK_INTERVAL_MS = 15 * 60 * 1000;
const REQUEST_TIMEOUT_MS = 10_000;

const deployments = [
  { environment: 'production', apiUrl: 'https://api.nadeshiko.co', frontendUrl: 'https://nadeshiko.co' },
  { environment: 'staging', apiUrl: 'https://api-stg.nadeshiko.co', frontendUrl: 'https://stg.nadeshiko.co' },
] as const;
const providers = ['discord', 'google'] as const;

type Provider = (typeof providers)[number];
type Environment = (typeof deployments)[number]['environment'];
type ResultKey = `${Provider}:${Environment}`;
type Fetch = typeof fetch;

const results = new Map<ResultKey, number>();
for (const provider of providers) {
  for (const deployment of deployments) results.set(`${provider}:${deployment.environment}`, 0);
}

getMeter()
  .createObservableGauge('nadeshiko.oauth_redirect.configured', {
    description: 'Whether an OAuth provider accepts the callback URL generated by Nadeshiko',
  })
  .addCallback((result) => {
    for (const [key, value] of results) {
      const [provider, environment] = key.split(':') as [Provider, Environment];
      result.observe(value, { provider, environment });
    }
  });

function expectedCallback(frontendUrl: string, provider: Provider): string {
  return `${frontendUrl}/v1/auth/callback/${provider}`;
}

async function generatedAuthorizationUrl(
  deployment: (typeof deployments)[number],
  provider: Provider,
  fetchFn: Fetch,
): Promise<URL> {
  const response = await fetchFn(`${deployment.apiUrl}/v1/auth/sign-in/social`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', origin: deployment.frontendUrl },
    body: JSON.stringify({ provider, callbackURL: '/' }),
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
  });
  if (!response.ok) throw new Error(`Nadeshiko returned HTTP ${response.status}`);

  const body = (await response.json()) as { url?: unknown };
  if (typeof body.url !== 'string') throw new Error('Nadeshiko returned no authorization URL');
  return new URL(body.url);
}

async function discordRedirects(fetchFn: Fetch): Promise<Set<string>> {
  const response = await fetchFn('https://discord.com/api/v10/oauth2/applications/@me', {
    headers: { authorization: `Bot ${BOT_CONFIG.token}` },
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
  });
  if (!response.ok) throw new Error(`Discord returned HTTP ${response.status}`);

  const application = (await response.json()) as { id?: unknown; redirect_uris?: unknown };
  if (application.id !== getApplicationId()) throw new Error('Discord returned a different application');
  if (!Array.isArray(application.redirect_uris)) throw new Error('Discord returned no redirect URI list');
  return new Set(application.redirect_uris.filter((uri): uri is string => typeof uri === 'string'));
}

async function checkGoogle(url: URL, fetchFn: Fetch): Promise<boolean> {
  const response = await fetchFn(url, {
    redirect: 'manual',
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
  });
  const location = response.headers.get('location');
  if (response.status !== 302 || !location) return false;

  const destination = new URL(location);
  return destination.hostname === 'accounts.google.com' && destination.pathname !== '/signin/oauth/error';
}

export async function checkOauthRedirects(fetchFn: Fetch = fetch): Promise<void> {
  let registeredDiscordRedirects: Set<string> | undefined;
  try {
    registeredDiscordRedirects = await discordRedirects(fetchFn);
  } catch (error) {
    log.warn({ err: error, provider: 'discord' }, 'Could not read OAuth application configuration');
  }

  await Promise.all(
    deployments.flatMap((deployment) =>
      providers.map(async (provider) => {
        const key: ResultKey = `${provider}:${deployment.environment}`;
        try {
          const authorizationUrl = await generatedAuthorizationUrl(deployment, provider, fetchFn);
          const callback = expectedCallback(deployment.frontendUrl, provider);
          const generatedCallback = authorizationUrl.searchParams.get('redirect_uri');
          const configured =
            generatedCallback === callback &&
            (provider === 'discord'
              ? registeredDiscordRedirects?.has(callback) === true
              : await checkGoogle(authorizationUrl, fetchFn));
          results.set(key, configured ? 1 : 0);
          if (!configured)
            log.warn({ provider, environment: deployment.environment, callback }, 'OAuth redirect rejected');
        } catch (error) {
          results.set(key, 0);
          log.warn({ err: error, provider, environment: deployment.environment }, 'OAuth redirect check failed');
        }
      }),
    ),
  );
}

export function startOauthRedirectMonitor(fetchFn: Fetch = fetch): { stop(): void } {
  void checkOauthRedirects(fetchFn);
  const timer = setInterval(() => void checkOauthRedirects(fetchFn), CHECK_INTERVAL_MS);
  timer.unref();
  return { stop: () => clearInterval(timer) };
}
