servers:
  web:
    hosts:
      - nadeshiko
    proxy: false

registry:
  server: ghcr.io
  username: kamal
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

ssh:
  user: docker

aliases:
  logs: app logs -f
