import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Drops three pieces of schema that nothing reads.
 *
 * 1. `ApiAuth` / `ApiAuthPermission` — the pre-better-auth API key tables.
 *    `1742200000000-better-auth-api-key-v2` moved key storage to better-auth's
 *    own `apikey` table; since then authentication has resolved keys through
 *    `authenticateBetterAuthApiKey` and read scopes from better-auth metadata,
 *    so these two tables have been write-nothing/read-nothing. Any token still
 *    sitting in them already could not authenticate.
 *    Note this drops the `api_permission_enum` *Postgres type* as well, which
 *    only ever backed `ApiAuthPermission.api_permission`. The `ApiPermission`
 *    TypeScript enum is unrelated and very much alive — it is the scope
 *    vocabulary for better-auth keys.
 *
 * 2. `User.last_login` — never written and never read. better-auth's field
 *    mapping has no login-timestamp entry, so the column is all NULL.
 *
 * 3. `WordFrequency.reading` — written by scripts/seed-word-frequency.ts and
 *    read by nothing: every query against this table names its columns and
 *    omits it, and the API exposes only rank/word/matchCount.
 *
 * 4. `CollectionSegment.note` — an annotation the API accepted but never
 *    returned. No client ever sent one (neither the site nor the bot exposes a
 *    field for it) and the response schema that would have carried it was
 *    orphaned, so the feature was specced and half-built rather than used.
 */
export class DropLegacyApiAuthAndUnreadColumns1746700000000 implements MigrationInterface {
  name = 'DropLegacyApiAuthAndUnreadColumns1746700000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Child first: ApiAuthPermission holds the FK to ApiAuth.
    await queryRunner.query(`DROP TABLE IF EXISTS "ApiAuthPermission"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "ApiAuth"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "api_permission_enum"`);

    await queryRunner.query(`ALTER TABLE "User" DROP COLUMN IF EXISTS "last_login"`);
    await queryRunner.query(`ALTER TABLE "WordFrequency" DROP COLUMN IF EXISTS "reading"`);
    await queryRunner.query(`ALTER TABLE "CollectionSegment" DROP COLUMN IF EXISTS "note"`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Shape only. The dropped rows and column values cannot be reconstructed —
    // though `last_login` was entirely NULL, and `WordFrequency.reading` is
    // regenerated by re-running scripts/seed-word-frequency.ts.
    await queryRunner.query(`ALTER TABLE "CollectionSegment" ADD COLUMN IF NOT EXISTS "note" character varying(500)`);
    await queryRunner.query(`ALTER TABLE "WordFrequency" ADD COLUMN IF NOT EXISTS "reading" character varying(50)`);
    await queryRunner.query(`ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "last_login" TIMESTAMP`);

    await queryRunner.query(`
      DO $$ BEGIN
        CREATE TYPE "api_permission_enum" AS ENUM (
          'ADD_MEDIA', 'READ_MEDIA', 'REMOVE_MEDIA', 'UPDATE_MEDIA',
          'READ_COLLECTIONS', 'CREATE_COLLECTIONS', 'UPDATE_COLLECTIONS', 'DELETE_COLLECTIONS',
          'READ_PROFILE', 'WRITE_PROFILE', 'READ_ACTIVITY', 'WRITE_ACTIVITY'
        );
      EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "ApiAuth" (
        "id" SERIAL PRIMARY KEY,
        "name" character varying,
        "hint" character varying,
        "token" character varying NOT NULL,
        "is_active" boolean NOT NULL DEFAULT true,
        "user_id" integer,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "ApiAuth_user_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "ApiAuthPermission" (
        "id" SERIAL PRIMARY KEY,
        "api_auth_id" integer NOT NULL,
        "api_permission" "api_permission_enum" NOT NULL,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "ApiAuthPermission_apiAuth_fkey" FOREIGN KEY ("api_auth_id") REFERENCES "ApiAuth"("id")
      )
    `);
  }
}
