FROM docker.elastic.co/elasticsearch/elasticsearch:9.4.1@sha256:268f65f1b32ea367e49c9be2acab144011b8c66c462c890f6190707743199050
RUN bin/elasticsearch-plugin install analysis-icu
# Sudachi 3.6 declares read access to config/sudachi; --batch accepts that
# reviewed entitlement so image builds remain non-interactive.
ADD --chown=elasticsearch:root --chmod=0644 \
  --checksum=sha256:ec46ddefc74743a4efd68f36af999ef39ed374312a82469f48690b271c32a1e6 \
  https://github.com/WorksApplications/elasticsearch-sudachi/releases/download/v3.6.0/elasticsearch-9.4.1-analysis-sudachi-3.6.0.zip \
  /tmp/elasticsearch-analysis-sudachi.zip
RUN bin/elasticsearch-plugin install --batch file:///tmp/elasticsearch-analysis-sudachi.zip && \
  rm /tmp/elasticsearch-analysis-sudachi.zip
USER root
ADD --checksum=sha256:2a1eda5a0240a42f45daf8003d97df5565c5d252bb2d58e71807bbbd082f7eea \
  https://github.com/WorksApplications/SudachiDict/releases/download/v20260116/sudachi-dictionary-20260116-full.zip \
  /tmp/sudachi-dict-full.zip
# Elasticsearch 9.4.1 is RHEL-based and already includes unzip.
RUN mkdir -p config/sudachi && \
  unzip /tmp/sudachi-dict-full.zip -d /tmp/sudachi-dict && \
  mv /tmp/sudachi-dict/*/system_full.dic config/sudachi/system_core.dic && \
  chown -R elasticsearch:elasticsearch config/sudachi && \
  rm -rf /tmp/sudachi-dict-full.zip /tmp/sudachi-dict
USER elasticsearch
