apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- brigadasos-db-dev.yaml
- pgroonga.yaml
- pgsync.yaml
#  - ../../base
namespace: nadedb-dev
images:
- name: brigadasos-dev-db
  newName: ghcr.io/brigadasos/nadeshiko
  newTag: v0.9.9.2.2-dev
- name: nadedb
  newName: ghcr.io/brigadasos/nadedb
  newTag: v0.9.1-4
