apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsync-data
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nvme1/nadedb/pgsync/"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgsync
spec:
  serviceName: pgsyc
  replicas: 1
  selector:
    matchLabels:
      app: pgsync
  template:
    metadata:
      labels:
        app: pgsync
    spec:
      containers:
        - name: pgsync
          image: natsume197/pgsync:3.2.1
          # bootstrap 
          command: [ "bootstrap"]
          args: ["--config", "/data/schema.json", "--daemon"]
          # loop forever, outputting "yo" every 5 seconds
          # command: [ "sh", "-c"]
          # args: ["while true; do echo 'yo' && sleep 5; done;"]
          envFrom:
            - configMapRef:
                name: pgsync-config
          volumeMounts:
            - name: pgsync-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: pgsync-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-storage"
        resources:
          requests:
            storage: 100Mi
