apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://nadeshiko-backend-prod-prometheus:9090
    isDefault: true
    editable: false
    uid: prometheus
    jsonData:
      timeInterval: "15s"
      httpMethod: "POST"
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo

  - name: Loki
    type: loki
    access: proxy
    url: http://nadeshiko-backend-prod-loki:3100
    editable: false
    uid: loki
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"traceId":"(\w+)"'
          url: "$${__value.raw}"
          datasourceUid: tempo
          matcherType: regex

  - name: Tempo
    type: tempo
    access: proxy
    url: http://nadeshiko-backend-prod-tempo:3200
    editable: false
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: prometheus
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
